{"summary":"关闭PolarDB for AI功能。","methods":["post"],"schemes":["http","https"],"security":[{"AK":[]}],"operationType":"readAndWrite","deprecated":false,"systemTags":{"operationType":"update"},"parameters":[{"name":"RegionId","in":"query","schema":{"description":"地域ID。","type":"string","required":true,"example":"cn-hangzhou"}},{"name":"DBClusterId","in":"query","schema":{"description":"集群ID。","type":"string","required":true,"example":"pc-**************"}}],"responses":{"200":{"schema":{"title":"Schema of Response","description":"Schema of Response","type":"object","properties":{"RequestId":{"title":"Id of the request","description":"请求ID。","type":"string","example":"936C7025-27A5-4CB1-BB31-540E1F0CCA12"},"TaskId":{"description":"任务ID。","type":"string","example":"53879cdb-9a00-428e-acaf-ff4cff******"}}}}},"errorCodes":{"400":[{"errorCode":"CallDB4AI.Error","errorMessage":"Call db4ai api error."}],"403":[{"errorCode":"OperationDenied.ClusterCategory","errorMessage":"The operation is not permitted due to cluster category."}],"404":[{"errorCode":"InvalidDBCluster.NotFound","errorMessage":"The DBClusterId provided does not exist in our records."},{"errorCode":"InvalidDBClusterId.Malformed","errorMessage":"The specified parameter DBClusterId is not valid."}]},"responseDemo":"[{\"type\":\"json\",\"example\":\"{\\n  \\\"RequestId\\\": \\\"936C7025-27A5-4CB1-BB31-540E1F0CCA12\\\",\\n  \\\"TaskId\\\": \\\"53879cdb-9a00-428e-acaf-ff4cff******\\\"\\n}\",\"errorExample\":\"\"},{\"type\":\"xml\",\"example\":\"<CloseAITaskResponse>\\n    <RequestId>936C7025-27A5-4CB1-BB31-540E1F0CCA12</RequestId>\\n    <TaskId>53879cdb-9a00-428e-acaf-ff4cff******</TaskId>\\n</CloseAITaskResponse>\",\"errorExample\":\"\"}]","title":"关闭AI任务"}