{"methods":["post","get"],"schemes":["http","https"],"security":[{"AK":[]}],"systemTags":{"operationType":"create"},"parameters":[{"name":"IotInstanceId","in":"query","schema":{"description":"实例ID。您可在物联网平台控制台的**实例概览**页面，查看当前实例的**ID**。\n\n><notice>\n- 若有ID值，必须传入该ID值，否则调用会失败。\n- 若无**实例概览**页面或ID值，则无需传入。\n\n></notice>\n\n实例的更多信息，请参见[实例概述](~~356505~~)。","type":"string","required":false,"example":"iot-w2****"}},{"name":"Name","in":"query","schema":{"description":"数据源名称，支持中文、英文字母、日文、数字、下划线（_）和短划线（-），长度为1~30个字符，一个中文及日文占2个字符。","type":"string","required":true,"example":"DataSource"}},{"name":"Description","in":"query","schema":{"description":"数据源描述信息。","type":"string","required":false,"example":"设备数据。"}}],"responses":{"200":{"schema":{"type":"object","properties":{"Code":{"description":"调用失败时，返回的错误码。更多信息，请参见[错误码](~~87387~~)。","type":"string","example":"iot.system.SystemException"},"ErrorMessage":{"description":"调用失败时，返回的出错信息。","type":"string","example":"系统异常"},"RequestId":{"description":"阿里云为该请求生成的唯一标识符。","type":"string","example":"291438BA-6E10-4C4C-B761-243B9A0D324F"},"Success":{"description":"表示是否调用成功。\n- **true**：调用成功。\n- **false**：调用失败。","type":"boolean","example":"true"},"DataSource":{"description":"创建数据源成功后，返回的数据源信息。","type":"object","properties":{"UtcCreated":{"description":"创建数据源的UTC时间。格式为`yyyy-MM-dd'T'HH:mm:ss.SSS'Z'`。","type":"string","example":"2022-03-27T12:45:43.000Z"},"Name":{"description":"数据源名称。","type":"string","example":"DataSource"},"Description":{"description":"数据源描述信息。","type":"string","example":"设备数据。"},"DataSourceId":{"description":"数据源ID。","type":"integer","format":"int64","example":"1001"}}}}}}},"errorCodes":{"400":[{"errorCode":"iot.system.SystemException","errorMessage":"An internal error occurred. Try again later."},{"errorCode":"iot.system.IllegalRequest","errorMessage":"The request parameter is invalid."},{"errorCode":"iot.rule.CreateRuleException","errorMessage":"An exception occurred while creating the rule."},{"errorCode":"iot.rule.DataSourceCountExceed","errorMessage":"The count of data source exceeds the maximum number"},{"errorCode":"iot.rule.DataSourceExists","errorMessage":"Same datasource is existed"},{"errorCode":"iot.rule.InvalidDataSourceName","errorMessage":"The data source name is invalid"},{"errorCode":"iot.common.TooManyRequest","errorMessage":"Request frequency is too high"}]},"responseDemo":"[{\"type\":\"json\",\"example\":\"{\\n  \\\"Code\\\": \\\"iot.system.SystemException\\\",\\n  \\\"ErrorMessage\\\": \\\"系统异常\\\",\\n  \\\"RequestId\\\": \\\"291438BA-6E10-4C4C-B761-243B9A0D324F\\\",\\n  \\\"Success\\\": true,\\n  \\\"DataSource\\\": {\\n    \\\"UtcCreated\\\": \\\"2022-03-27T12:45:43.000Z\\\",\\n    \\\"Name\\\": \\\"DataSource\\\",\\n    \\\"Description\\\": \\\"设备数据。\\\",\\n    \\\"DataSourceId\\\": 1001\\n  }\\n}\",\"errorExample\":\"\"},{\"type\":\"xml\",\"example\":\"<CreateParserDataSourceResponse>\\n<RequestId>291438BA-6E10-4C4C-B761-243B9A0D324F</RequestId>\\n<Success>true</Success>\\n<DataSource>\\n    <Description>设备数据。</Description>\\n    <UtcCreated>2022-03-27T12:45:43.000Z</UtcCreated>\\n    <DataSourceId>1001</DataSourceId>\\n    <Name>DataSource</Name>\\n</DataSource>\\n</CreateParserDataSourceResponse>\",\"errorExample\":\"\"}]","title":"CreateParserDataSource","summary":"调用该接口创建待流转的数据源。","description":"## QPS限制\n\n单个阿里云账号调用该接口的每秒请求数（QPS）最大限制为10。\n> RAM用户共享阿里云账号配额。","requestParamsDescription":"调用API时，除了本文介绍的该API的特有请求参数，还需传入公共请求参数。公共请求参数说明，请参见[公共参数文档](~~30561~~)。","responseParamsDescription":" ","extraInfo":" "}